// water -  https://images.pexels.com/photos/3875525/pexels-photo-3875525.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2
// tea - https://media.istockphoto.com/id/1093080584/photo/rosemary-tea-in-glass-tea-cup-on-rustic-wooden-table-closeup-herbal-vitamin-tea.jpg?s=612x612&w=0&k=20&c=vhwN5cb7ql5st2Wv5OjnWYwGl8EdiiFaKMZEXuYsqvk=
// coffee - https://images.pexels.com/photos/6166819/pexels-photo-6166819.jpeg?auto=compress&cs=tinysrgb&w=800
// juice - https://media.istockphoto.com/id/1396946898/photo/red-sweet-watermelon-juice-from-ripe-watermelon-berries.jpg?s=612x612&w=0&k=20&c=ILz4hNpArY-w48at1AcUZfrMmxg84LuAa_9T0yTyYyA=
// webFlow - https://webflow.com/made-in-webflow/website/ljs-radical-project-78f506?ref=made-in-webflow-search&searchValue=restaurant



const healthySmoothies = [
  {
    id: 1,
    name: "Infused Water",
    starsRatings: "",
    price: "",
    imageURL: "https://images.pexels.com/photos/9009821/pexels-photo-9009821.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    protein: "0g",
    calories: "5",
    fats: "0g",
    carbs: "1g",
    category: "Pre-Workout",
  },
  {
    id: 2,
    name: "Coconut Water",
    starsRatings: "",
    price: "",
    imageURL: "https://images.pexels.com/photos/19035106/pexels-photo-19035106/free-photo-of-cocktail-in-coconut-shell.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    protein: "1g",
    calories: "60",
    fats: "0.5g",
    carbs: "15g",
    category: "Post-Workout",
  },
  {
    id: 3,
    name: "Aloe Vera Water",
    starsRatings: "",
    price: "",
    imageURL: "https://media.istockphoto.com/id/876902650/photo/lemonade-from-lime-and-mint.jpg?s=612x612&w=0&k=20&c=9Pd1U7FGY7taqoBR-YZJP9YPiBFlQ-4s8ME7I9p8K5U=",
    protein: "0g",
    calories: "25",
    fats: "0g",
    carbs: "6g",
    category: "Pre-Workout",
  },
  {
    id: 4,
    name: "Chia Seed Water",
    starsRatings: "",
    price: "",
    imageURL: "https://media.istockphoto.com/id/1300848289/photo/water-with-chia-seeds-and-lemon-on-a-black-background-a-useful-drink-for-weight-loss.jpg?s=612x612&w=0&k=20&c=OdhwZaf_sOOPfCQJxdh01mXodTSQ7REUC876v_hc0Mw=",
    protein: "3g",
    calories: "100",
    fats: "7g",
    carbs: "8g",
    category: "High in Protein",
  },
  {
    id: 5,
    name: "Herbal Infused Water",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "0g",
    calories: "5",
    fats: "0g",
    carbs: "1g",
    category: "Pre-Workout",
  },
  {
    id: 6,
    name: "Green Smoothie",
    starsRatings: "",
    price: "",
    imageURL: "https://images.pexels.com/photos/5337721/pexels-photo-5337721.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    protein: "5g",
    calories: "180",
    fats: "2g",
    carbs: "38g",
    category: "Post-Workout",
  },
  {
    id: 7,
    name: "Protein Smoothie",
    starsRatings: "",
    price: "",
    imageURL: "https://images.pexels.com/photos/11161212/pexels-photo-11161212.jpeg?auto=compress&cs=tinysrgb&w=800",
    protein: "15g",
    calories: "250",
    fats: "5g",
    carbs: "30g",
    category: "High in Protein",
  },
  {
    id: 8,
    name: "Berry Smoothie",
    starsRatings: "",
    price: "",
    imageURL: "https://images.pexels.com/photos/27089116/pexels-photo-27089116/free-photo-of-close-up-of-a-glass-with-a-strawberry-smoothie.jpeg?auto=compress&cs=tinysrgb&w=800",
    protein: "8g",
    calories: "160",
    fats: "2g",
    carbs: "28g",
    category: "Post-Workout",
  },
  {
    id: 9,
    name: "Tropical Smoothie",
    starsRatings: "",
    price: "",
    imageURL: "https://images.pexels.com/photos/5668538/pexels-photo-5668538.jpeg?auto=compress&cs=tinysrgb&w=800",
    protein: "3g",
    calories: "190",
    fats: "4g",
    carbs: "35g",
    category: "Post-Workout",
  },
  {
    id: 10,
    name: "Peanut Butter & Banana Smoothie",
    starsRatings: "",
    price: "",
    imageURL: "https://media.istockphoto.com/id/1023939600/photo/banana-protein-smoothie-or-milkshake-in-drinking-glass.jpg?s=612x612&w=0&k=20&c=ZxE9quu0acZbkfgwKOPiLwMcANarhTkIeD0iHyAFIUQ=",
    protein: "10g",
    calories: "300",
    fats: "15g",
    carbs: "35g",
    category: "High in Protein",
  },
  {
    id: 11,
    name: "Freshly Squeezed Orange Juice",
    starsRatings: "",
    price: "",
    imageURL: "https://media.istockphoto.com/id/1206052727/photo/homemade-orange-juice-in-a-mason-jar-shot-on-rustic-wooden-table.jpg?s=612x612&w=0&k=20&c=7RU0tOKi_tBgusSIs5UmMiHRddncvyeZ0V5EPny0Ajs=",
    protein: "2g",
    calories: "150",
    fats: "0.5g",
    carbs: "30g",
    category: "Pre-Workout",
  },
  {
    id: 12,
    name: "Carrot & Ginger Juice",
    starsRatings: "",
    price: "",
    imageURL: "https://media.istockphoto.com/id/507843754/photo/fresh-carrot-juice-in-a-glass-jar-healthy-food.jpg?s=612x612&w=0&k=20&c=PV5Kn2DcfsFOVFIhzfY41DbAJ8rqGITopVGPVSILiP0=",
    protein: "2g",
    calories: "90",
    fats: "0g",
    carbs: "22g",
    category: "Pre-Workout",
  },
  {
    id: 13,
    name: "Beetroot Juice",
    starsRatings: "",
    price: "",
    imageURL: "https://media.istockphoto.com/id/606020604/photo/smoothie-with-beetroot-spinach-and-lemon.jpg?s=612x612&w=0&k=20&c=QI-O7qGDJ4AnFzze-kKr9FRwYVZgbqnwZaqQZbgyVLg=",
    protein: "2g",
    calories: "100",
    fats: "0g",
    carbs: "24g",
    category: "Pre-Workout",
  },
  {
    id: 14,
    name: "Cucumber & Mint Juice",
    starsRatings: "",
    price: "",
    imageURL: "https://media.istockphoto.com/id/1340698040/photo/green-smoothie-with-cucumber-in-a-glass-jar-fresh-ripe-vegetables-greens-and-chia-seeds.jpg?s=612x612&w=0&k=20&c=mU7fCMZgE7BfQ_URwkjIo28bff25EfvKaXpP_Rg9KUI=",
    protein: "1g",
    calories: "30",
    fats: "0g",
    carbs: "7g",
    category: "Pre-Workout",
  },
  {
    id: 15,
    name: "Celery Juice",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "1g",
    calories: "50",
    fats: "0g",
    carbs: "11g",
    category: "Pre-Workout",
  },
  {
    id: 16,
    name: "Apple & Spinach Juice",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "3g",
    calories: "120",
    fats: "1g",
    carbs: "24g",
    category: "Post-Workout",
  },
  {
    id: 17,
    name: "Green Tea",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "0g",
    calories: "0",
    fats: "0g",
    carbs: "0g",
    category: "Pre-Workout",
  },
  {
    id: 18,
    name: "Matcha Tea",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "1g",
    calories: "20",
    fats: "0g",
    carbs: "3g",
    category: "Pre-Workout",
  },
  {
    id: 19,
    name: "Herbal Tea",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "0g",
    calories: "2",
    fats: "0g",
    carbs: "0.5g",
    category: "Pre-Workout",
  },
  {
    id: 20,
    name: "Ginger Tea",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "0g",
    calories: "5",
    fats: "0g",
    carbs: "1g",
    category: "Pre-Workout",
  },
  {
    id: 21,
    name: "Turmeric Tea",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "0g",
    calories: "10",
    fats: "0g",
    carbs: "2g",
    category: "Pre-Workout",
  },
  {
    id: 22,
    name: "Lemon Balm Tea",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "0g",
    calories: "3",
    fats: "0g",
    carbs: "1g",
    category: "Pre-Workout",
  },
  {
    id: 23,
    name: "White Tea",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "0g",
    calories: "0",
    fats: "0g",
    carbs: "0g",
    category: "Pre-Workout",
  },
  {
    id: 24,
    name: "Almond Milk",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "1g",
    calories: "40",
    fats: "3g",
    carbs: "1g",
    category: "Post-Workout",
  },
  {
    id: 25,
    name: "Oat Milk",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "3g",
    calories: "120",
    fats: "5g",
    carbs: "16g",
    category: "High in Calories",
  },
  {
    id: 26,
    name: "Coconut Milk",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "1g",
    calories: "150",
    fats: "15g",
    carbs: "6g",
    category: "High in Calories",
  },
  {
    id: 27,
    name: "Cashew Milk",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "1g",
    calories: "60",
    fats: "4g",
    carbs: "5g",
    category: "Post-Workout",
  },
  {
    id: 28,
    name: "Soy Milk",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "8g",
    calories: "130",
    fats: "4g",
    carbs: "10g",
    category: "High in Protein",
  },
  {
    id: 29,
    name: "Lemon & Ginger Detox Water",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "0g",
    calories: "10",
    fats: "0g",
    carbs: "2g",
    category: "Pre-Workout",
  },
  {
    id: 30,
    name: "Cucumber & Mint Detox Drink",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "0g",
    calories: "8",
    fats: "0g",
    carbs: "2g",
    category: "Pre-Workout",
  },
  {
    id: 31,
    name: "Apple Cider Vinegar Drink",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "0g",
    calories: "5",
    fats: "0g",
    carbs: "2g",
    category: "Pre-Workout",
  },
  {
    id: 32,
    name: "Charcoal Lemonade",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "0g",
    calories: "25",
    fats: "0g",
    carbs: "6g",
    category: "Pre-Workout",
  },
  {
    id: 33,
    name: "Electrolyte Drink",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "0g",
    calories: "30",
    fats: "0g",
    carbs: "7g",
    category: "Post-Workout",
  },
  {
    id: 34,
    name: "Cucumber & Basil Water",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "0g",
    calories: "5",
    fats: "0g",
    carbs: "1g",
    category: "Pre-Workout",
  },
  {
    id: 35,
    name: "Ginger Lemon Water",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "0g",
    calories: "12",
    fats: "0g",
    carbs: "3g",
    category: "Pre-Workout",
  },
  {
    id: 36,
    name: "Whey Protein Shake",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "24g",
    calories: "120",
    fats: "2g",
    carbs: "5g",
    category: "High in Protein",
  },
  {
    id: 37,
    name: "Recovery Smoothie",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "8g",
    calories: "200",
    fats: "4g",
    carbs: "30g",
    category: "Post-Workout",
  },
  {
    id: 38,
    name: "Protein Shakes",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "25g",
    calories: "200",
    fats: "5g",
    carbs: "8g",
    category: "High in Protein",
  },
  {
    id: 39,
    name: "Energy Smoothie",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "10g",
    calories: "280",
    fats: "12g",
    carbs: "35g",
    category: "High in Calories",
  },
  {
    id: 40,
    name: "Pre-Workout Drink",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "1g",
    calories: "90",
    fats: "0g",
    carbs: "23g",
    category: "Pre-Workout",
  },
  {
    id: 41,
    name: "Flaxseed Drink",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "2g",
    calories: "80",
    fats: "5g",
    carbs: "7g",
    category: "Post-Workout",
  },
  {
    id: 42,
    name: "Hemp Milk",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "4g",
    calories: "60",
    fats: "5g",
    carbs: "3g",
    category: "Post-Workout",
  },
  {
    id: 43,
    name: "Chia Fresca",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "2g",
    calories: "100",
    fats: "5g",
    carbs: "10g",
    category: "Post-Workout",
  },
  {
    id: 44,
    name: "Sesame Milk",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "3g",
    calories: "80",
    fats: "7g",
    carbs: "3g",
    category: "Post-Workout",
  },
  {
    id: 45,
    name: "Adaptogen Drink",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "0g",
    calories: "15",
    fats: "0g",
    carbs: "3g",
    category: "Pre-Workout",
  },
  {
    id: 46,
    name: "Collagen-Infused Drink",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "10g",
    calories: "50",
    fats: "0g",
    carbs: "2g",
    category: "High in Protein",
  },
  {
    id: 47,
    name: "CBD-Infused Water",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "0g",
    calories: "5",
    fats: "0g",
    carbs: "1g",
    category: "Pre-Workout",
  },
  {
    id: 48,
    name: "Electrolyte Water",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "0g",
    calories: "20",
    fats: "0g",
    carbs: "4g",
    category: "Post-Workout",
  },
  {
    id: 49,
    name: "Golden Milk (Turmeric Latte)",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "4g",
    calories: "120",
    fats: "8g",
    carbs: "10g",
    category: "Post-Workout",
  },
  {
    id: 50,
    name: "Cinnamon Tea",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "0g",
    calories: "10",
    fats: "0g",
    carbs: "2g",
    category: "Pre-Workout",
  },
  {
    id: 51,
    name: "Spiced Apple Cider",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "0g",
    calories: "120",
    fats: "0g",
    carbs: "30g",
    category: "Pre-Workout",
  },
  {
    id: 52,
    name: "Chai Latte",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "4g",
    calories: "130",
    fats: "4g",
    carbs: "22g",
    category: "Post-Workout",
  },
  {
    id: 53,
    name: "Nettle Tea",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "0g",
    calories: "5",
    fats: "0g",
    carbs: "1g",
    category: "Pre-Workout",
  },
  {
    id: 54,
    name: "Dandelion Root Tea",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "0g",
    calories: "5",
    fats: "0g",
    carbs: "1g",
    category: "Pre-Workout",
  },
  {
    id: 55,
    name: "Hibiscus Iced Tea",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "0g",
    calories: "60",
    fats: "0g",
    carbs: "15g",
    category: "Post-Workout",
  },
  {
    id: 56,
    name: "Moringa Tea",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "0g",
    calories: "2",
    fats: "0g",
    carbs: "0g",
    category: "Pre-Workout",
  },
  {
    id: 57,
    name: "Licorice Root Tea",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "0g",
    calories: "10",
    fats: "0g",
    carbs: "2g",
    category: "Pre-Workout",
  },
  {
    id: 58,
    name: "Watermelon Juice",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "1g",
    calories: "85",
    fats: "0g",
    carbs: "22g",
    category: "Post-Workout",
  },
  {
    id: 59,
    name: "Pineapple & Ginger Juice",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "1g",
    calories: "100",
    fats: "0g",
    carbs: "25g",
    category: "Post-Workout",
  },
  {
    id: 60,
    name: "Grapefruit Juice",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "1g",
    calories: "90",
    fats: "0g",
    carbs: "23g",
    category: "Post-Workout",
  },
  {
    id: 61,
    name: "Pomegranate Juice",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "1g",
    calories: "120",
    fats: "0g",
    carbs: "30g",
    category: "Post-Workout",
  },
  {
    id: 62,
    name: "Acai Smoothie",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "4g",
    calories: "180",
    fats: "7g",
    carbs: "24g",
    category: "High in Calories",
  },
  {
    id: 63,
    name: "Yerba Mate",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "0g",
    calories: "5",
    fats: "0g",
    carbs: "1g",
    category: "Pre-Workout",
  },
  {
    id: 64,
    name: "Rooibos Tea",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "0g",
    calories: "0",
    fats: "0g",
    carbs: "0g",
    category: "Pre-Workout",
  },
  {
    id: 65,
    name: "Chicory Coffee",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "0g",
    calories: "5",
    fats: "0g",
    carbs: "1g",
    category: "Pre-Workout",
  },
  {
    id: 66,
    name: "Dandelion Coffee",
    starsRatings: "",
    price: "",
    imageURL: "",
    protein: "0g",
    calories: "10",
    fats: "0g",
    carbs: "2g",
    category: "Pre-Workout",
  },
];

const healthyBreakfasts = [
  {
    id: 1,
    name: "Paneer Bhurji",
    category: "Post-Workout",
    ingredients: ["Paneer", "Onions", "Tomatoes", "Green Chilies", "Spices"],
    "500g": {
      protein: "45g",
      calories: "420",
      energy: "1760kJ",
      carbs: "15g",
      fats: "22g",
    },
    "1kg": {
      protein: "90g",
      calories: "840",
      energy: "3520kJ",
      carbs: "30g",
      fats: "44g",
    },
  },
  {
    id: 2,
    name: "Moong Dal Chilla",
    category: "Pre-Workout",
    ingredients: ["Moong Dal", "Cumin", "Green Chilies", "Coriander"],
    "500g": {
      protein: "25g",
      calories: "250",
      energy: "1045kJ",
      carbs: "40g",
      fats: "4g",
    },
    "1kg": {
      protein: "50g",
      calories: "500",
      energy: "2090kJ",
      carbs: "80g",
      fats: "8g",
    },
  },
  {
    id: 3,
    name: "Sprouted Moong Salad",
    category: "Post-Workout",
    ingredients: [
      "Sprouted Moong Beans",
      "Cucumber",
      "Tomatoes",
      "Lemon",
      "Coriander",
    ],
    "500g": {
      protein: "24g",
      calories: "180",
      energy: "753kJ",
      carbs: "32g",
      fats: "2g",
    },
    "1kg": {
      protein: "48g",
      calories: "360",
      energy: "1506kJ",
      carbs: "64g",
      fats: "4g",
    },
  },
  {
    id: 4,
    name: "Egg White Omelette",
    category: "Pre-Workout",
    ingredients: ["Egg Whites", "Onions", "Bell Peppers", "Spinach"],
    "500g": {
      protein: "40g",
      calories: "200",
      energy: "836kJ",
      carbs: "10g",
      fats: "3g",
    },
    "1kg": {
      protein: "80g",
      calories: "400",
      energy: "1672kJ",
      carbs: "20g",
      fats: "6g",
    },
  },
  {
    id: 5,
    name: "Ragi Dosa with Chutney",
    category: "Pre-Workout",
    ingredients: ["Ragi Flour", "Yogurt", "Spices", "Coconut Chutney"],
    "500g": {
      protein: "18g",
      calories: "350",
      energy: "1464kJ",
      carbs: "60g",
      fats: "7g",
    },
    "1kg": {
      protein: "36g",
      calories: "700",
      energy: "2928kJ",
      carbs: "120g",
      fats: "14g",
    },
  },
  {
    id: 6,
    name: "Masoor Dal Pancakes",
    category: "Post-Workout",
    ingredients: ["Masoor Dal", "Spices", "Green Chilies", "Coriander"],
    "500g": {
      protein: "30g",
      calories: "270",
      energy: "1130kJ",
      carbs: "40g",
      fats: "5g",
    },
    "1kg": {
      protein: "60g",
      calories: "540",
      energy: "2260kJ",
      carbs: "80g",
      fats: "10g",
    },
  },
  {
    id: 7,
    name: "Besan Chilla",
    category: "Pre-Workout",
    ingredients: ["Besan (Chickpea Flour)", "Onions", "Tomatoes", "Spices"],
    "500g": {
      protein: "22g",
      calories: "230",
      energy: "962kJ",
      carbs: "35g",
      fats: "6g",
    },
    "1kg": {
      protein: "44g",
      calories: "460",
      energy: "1924kJ",
      carbs: "70g",
      fats: "12g",
    },
  },
  {
    id: 8,
    name: "Upma with Tofu",
    category: "Post-Workout",
    ingredients: ["Semolina", "Tofu", "Onions", "Spices"],
    "500g": {
      protein: "28g",
      calories: "300",
      energy: "1255kJ",
      carbs: "45g",
      fats: "7g",
    },
    "1kg": {
      protein: "56g",
      calories: "600",
      energy: "2510kJ",
      carbs: "90g",
      fats: "14g",
    },
  },
  {
    id: 9,
    name: "Quinoa Idli",
    category: "Pre-Workout",
    ingredients: ["Quinoa", "Urad Dal", "Fenugreek Seeds", "Spices"],
    "500g": {
      protein: "26g",
      calories: "310",
      energy: "1297kJ",
      carbs: "50g",
      fats: "4g",
    },
    "1kg": {
      protein: "52g",
      calories: "620",
      energy: "2594kJ",
      carbs: "100g",
      fats: "8g",
    },
  },
  {
    id: 10,
    name: "Egg Bhurji with Spinach",
    category: "Post-Workout",
    ingredients: ["Eggs", "Spinach", "Onions", "Tomatoes", "Spices"],
    "500g": {
      protein: "38g",
      calories: "290",
      energy: "1213kJ",
      carbs: "15g",
      fats: "10g",
    },
    "1kg": {
      protein: "76g",
      calories: "580",
      energy: "2426kJ",
      carbs: "30g",
      fats: "20g",
    },
  },
  {
    id: 11,
    name: "Oats Dosa",
    category: "Pre-Workout",
    ingredients: ["Oats", "Rice Flour", "Yogurt", "Spices"],
    "500g": {
      protein: "20g",
      calories: "280",
      energy: "1173kJ",
      carbs: "50g",
      fats: "5g",
    },
    "1kg": {
      protein: "40g",
      calories: "560",
      energy: "2346kJ",
      carbs: "100g",
      fats: "10g",
    },
  },
  {
    id: 12,
    name: "Poha with Peanuts",
    category: "Pre-Workout",
    ingredients: ["Flattened Rice", "Peanuts", "Curry Leaves", "Spices"],
    "500g": {
      protein: "15g",
      calories: "240",
      energy: "1005kJ",
      carbs: "40g",
      fats: "6g",
    },
    "1kg": {
      protein: "30g",
      calories: "480",
      energy: "2010kJ",
      carbs: "80g",
      fats: "12g",
    },
  },
  {
    id: 13,
    name: "Greek Yogurt Parfait",
    category: "Post-Workout",
    ingredients: ["Greek Yogurt", "Fruits", "Nuts", "Honey"],
    "500g": {
      protein: "30g",
      calories: "290",
      energy: "1213kJ",
      carbs: "40g",
      fats: "8g",
    },
    "1kg": {
      protein: "60g",
      calories: "580",
      energy: "2426kJ",
      carbs: "80g",
      fats: "16g",
    },
  },
  {
    id: 14,
    name: "Rava Upma with Sprouts",
    category: "Pre-Workout",
    ingredients: ["Semolina", "Sprouts", "Onions", "Spices"],
    "500g": {
      protein: "24g",
      calories: "300",
      energy: "1255kJ",
      carbs: "55g",
      fats: "6g",
    },
    "1kg": {
      protein: "48g",
      calories: "600",
      energy: "2510kJ",
      carbs: "110g",
      fats: "12g",
    },
  },
  {
    id: 15,
    name: "Tofu Scramble",
    category: "Post-Workout",
    ingredients: ["Tofu", "Onions", "Tomatoes", "Spices"],
    "500g": {
      protein: "35g",
      calories: "260",
      energy: "1087kJ",
      carbs: "20g",
      fats: "8g",
    },
    "1kg": {
      protein: "70g",
      calories: "520",
      energy: "2174kJ",
      carbs: "40g",
      fats: "16g",
    },
  },
  {
    id: 16,
    name: "Chickpea Pancakes",
    category: "Pre-Workout",
    ingredients: ["Chickpea Flour", "Spices", "Onions", "Coriander"],
    "500g": {
      protein: "30g",
      calories: "350",
      energy: "1464kJ",
      carbs: "50g",
      fats: "6g",
    },
    "1kg": {
      protein: "60g",
      calories: "700",
      energy: "2928kJ",
      carbs: "100g",
      fats: "12g",
    },
  },
  {
    id: 17,
    name: "Rajma Salad",
    category: "Post-Workout",
    ingredients: ["Boiled Kidney Beans", "Tomatoes", "Cucumber", "Spices"],
    "500g": {
      protein: "25g",
      calories: "260",
      energy: "1087kJ",
      carbs: "45g",
      fats: "3g",
    },
    "1kg": {
      protein: "50g",
      calories: "520",
      energy: "2174kJ",
      carbs: "90g",
      fats: "6g",
    },
  },
  {
    id: 18,
    name: "Masala Oats with Boiled Eggs",
    category: "Post-Workout",
    ingredients: ["Oats", "Boiled Eggs", "Spices", "Onions"],
    "500g": {
      protein: "32g",
      calories: "340",
      energy: "1423kJ",
      carbs: "45g",
      fats: "8g",
    },
    "1kg": {
      protein: "64g",
      calories: "680",
      energy: "2846kJ",
      carbs: "90g",
      fats: "16g",
    },
  },
  {
    id: 19,
    name: "Idli with Sambar (Dal based)",
    category: "Pre-Workout",
    ingredients: ["Rice", "Urad Dal", "Sambar", "Spices"],
    "500g": {
      protein: "20g",
      calories: "300",
      energy: "1255kJ",
      carbs: "50g",
      fats: "4g",
    },
    "1kg": {
      protein: "40g",
      calories: "600",
      energy: "2510kJ",
      carbs: "100g",
      fats: "8g",
    },
  },
  {
    id: 20,
    name: "Soya Bhurji",
    category: "Post-Workout",
    ingredients: ["Soya Granules", "Onions", "Tomatoes", "Spices"],
    "500g": {
      protein: "50g",
      calories: "360",
      energy: "1506kJ",
      carbs: "30g",
      fats: "7g",
    },
    "1kg": {
      protein: "100g",
      calories: "720",
      energy: "3012kJ",
      carbs: "60g",
      fats: "14g",
    },
  },
];

const dinnerMeal = [
  {
    id: 1,
    name: "Chickpea Curry (Chole)",
    category: "Veg",
    ingredients: ["Chickpeas", "Tomatoes", "Onions", "Spices", "Coriander"],
    "500g": {
      protein: "20g",
      calories: "250",
      energy: "1045kJ",
      carbs: "45g",
      fats: "5g",
    },
    "1kg": {
      protein: "40g",
      calories: "500",
      energy: "2090kJ",
      carbs: "90g",
      fats: "10g",
    },
  },
  {
    id: 2,
    name: "Palak Paneer",
    category: "Veg",
    ingredients: ["Paneer", "Spinach", "Onions", "Tomatoes", "Spices"],
    "500g": {
      protein: "30g",
      calories: "300",
      energy: "1255kJ",
      carbs: "20g",
      fats: "15g",
    },
    "1kg": {
      protein: "60g",
      calories: "600",
      energy: "2510kJ",
      carbs: "40g",
      fats: "30g",
    },
  },
  {
    id: 3,
    name: "Tofu Stir Fry",
    category: "Veg",
    ingredients: ["Tofu", "Bell Peppers", "Broccoli", "Carrots", "Spices"],
    "500g": {
      protein: "25g",
      calories: "220",
      energy: "920kJ",
      carbs: "20g",
      fats: "10g",
    },
    "1kg": {
      protein: "50g",
      calories: "440",
      energy: "1840kJ",
      carbs: "40g",
      fats: "20g",
    },
  },
  {
    id: 4,
    name: "Rajma (Kidney Bean Curry)",
    category: "Veg",
    ingredients: ["Kidney Beans", "Tomatoes", "Onions", "Spices"],
    "500g": {
      protein: "20g",
      calories: "280",
      energy: "1173kJ",
      carbs: "50g",
      fats: "4g",
    },
    "1kg": {
      protein: "40g",
      calories: "560",
      energy: "2346kJ",
      carbs: "100g",
      fats: "8g",
    },
  },
  {
    id: 5,
    name: "Grilled Chicken Breast",
    category: "Non-Veg",
    ingredients: ["Chicken Breast", "Spices", "Lemon", "Olive Oil"],
    "500g": {
      protein: "40g",
      calories: "300",
      energy: "1255kJ",
      carbs: "0g",
      fats: "7g",
    },
    "1kg": {
      protein: "80g",
      calories: "600",
      energy: "2510kJ",
      carbs: "0g",
      fats: "14g",
    },
  },
  {
    id: 6,
    name: "Fish Curry",
    category: "Non-Veg",
    ingredients: ["Fish", "Coconut Milk", "Tomatoes", "Spices"],
    "500g": {
      protein: "30g",
      calories: "250",
      energy: "1045kJ",
      carbs: "10g",
      fats: "12g",
    },
    "1kg": {
      protein: "60g",
      calories: "500",
      energy: "2090kJ",
      carbs: "20g",
      fats: "24g",
    },
  },
  {
    id: 7,
    name: "Chicken Tikka",
    category: "Non-Veg",
    ingredients: ["Chicken", "Yogurt", "Spices", "Lemon"],
    "500g": {
      protein: "35g",
      calories: "300",
      energy: "1255kJ",
      carbs: "5g",
      fats: "10g",
    },
    "1kg": {
      protein: "70g",
      calories: "600",
      energy: "2510kJ",
      carbs: "10g",
      fats: "20g",
    },
  },
  {
    id: 8,
    name: "Egg Curry",
    category: "Non-Veg",
    ingredients: ["Eggs", "Tomatoes", "Onions", "Spices"],
    "500g": {
      protein: "30g",
      calories: "250",
      energy: "1045kJ",
      carbs: "20g",
      fats: "10g",
    },
    "1kg": {
      protein: "60g",
      calories: "500",
      energy: "2090kJ",
      carbs: "40g",
      fats: "20g",
    },
  },
  {
    id: 9,
    name: "Lentil Soup",
    category: "Veg",
    ingredients: ["Lentils", "Carrots", "Celery", "Spices"],
    "500g": {
      protein: "20g",
      calories: "200",
      energy: "836kJ",
      carbs: "30g",
      fats: "3g",
    },
    "1kg": {
      protein: "40g",
      calories: "400",
      energy: "1672kJ",
      carbs: "60g",
      fats: "6g",
    },
  },
  {
    id: 10,
    name: "Stuffed Bell Peppers with Quinoa",
    category: "Veg",
    ingredients: ["Bell Peppers", "Quinoa", "Tomatoes", "Spices"],
    "500g": {
      protein: "18g",
      calories: "220",
      energy: "920kJ",
      carbs: "35g",
      fats: "4g",
    },
    "1kg": {
      protein: "36g",
      calories: "440",
      energy: "1840kJ",
      carbs: "70g",
      fats: "8g",
    },
  },
  {
    id: 11,
    name: "Masoor Dal (Red Lentil Curry)",
    category: "Veg",
    ingredients: ["Red Lentils", "Tomatoes", "Onions", "Spices"],
    "500g": {
      protein: "22g",
      calories: "240",
      energy: "1005kJ",
      carbs: "40g",
      fats: "4g",
    },
    "1kg": {
      protein: "44g",
      calories: "480",
      energy: "2010kJ",
      carbs: "80g",
      fats: "8g",
    },
  },
  {
    id: 12,
    name: "Sprouted Moong Dal Salad",
    category: "Veg",
    ingredients: ["Sprouted Moong Dal", "Tomatoes", "Cucumber", "Spices"],
    "500g": {
      protein: "18g",
      calories: "190",
      energy: "796kJ",
      carbs: "30g",
      fats: "2g",
    },
    "1kg": {
      protein: "36g",
      calories: "380",
      energy: "1592kJ",
      carbs: "60g",
      fats: "4g",
    },
  },
  {
    id: 13,
    name: "Quinoa and Vegetable Stir Fry",
    category: "Veg",
    ingredients: ["Quinoa", "Mixed Vegetables", "Soy Sauce", "Spices"],
    "500g": {
      protein: "20g",
      calories: "270",
      energy: "1130kJ",
      carbs: "45g",
      fats: "6g",
    },
    "1kg": {
      protein: "40g",
      calories: "540",
      energy: "2260kJ",
      carbs: "90g",
      fats: "12g",
    },
  },
  {
    id: 14,
    name: "Grilled Tandoori Paneer",
    category: "Veg",
    ingredients: ["Paneer", "Yogurt", "Tandoori Masala", "Lemon"],
    "500g": {
      protein: "30g",
      calories: "350",
      energy: "1464kJ",
      carbs: "10g",
      fats: "15g",
    },
    "1kg": {
      protein: "60g",
      calories: "700",
      energy: "2928kJ",
      carbs: "20g",
      fats: "30g",
    },
  },
  {
    id: 15,
    name: "Lentil and Spinach Soup",
    category: "Veg",
    ingredients: ["Lentils", "Spinach", "Onions", "Spices"],
    "500g": {
      protein: "22g",
      calories: "210",
      energy: "879kJ",
      carbs: "35g",
      fats: "3g",
    },
    "1kg": {
      protein: "44g",
      calories: "420",
      energy: "1758kJ",
      carbs: "70g",
      fats: "6g",
    },
  },
  {
    id: 16,
    name: "Chicken Saag",
    category: "Non-Veg",
    ingredients: ["Chicken", "Spinach", "Onions", "Tomatoes", "Spices"],
    "500g": {
      protein: "35g",
      calories: "320",
      energy: "1345kJ",
      carbs: "15g",
      fats: "12g",
    },
    "1kg": {
      protein: "70g",
      calories: "640",
      energy: "2690kJ",
      carbs: "30g",
      fats: "24g",
    },
  },
  {
    id: 17,
    name: "Baked Fish with Herbs",
    category: "Non-Veg",
    ingredients: ["Fish", "Herbs", "Lemon", "Olive Oil"],
    "500g": {
      protein: "35g",
      calories: "280",
      energy: "1173kJ",
      carbs: "5g",
      fats: "6g",
    },
    "1kg": {
      protein: "70g",
      calories: "560",
      energy: "2346kJ",
      carbs: "10g",
      fats: "12g",
    },
  },
  {
    id: 18,
    name: "Turkey Meatballs with Tomato Sauce",
    category: "Non-Veg",
    ingredients: ["Turkey Mince", "Tomatoes", "Onions", "Spices"],
    "500g": {
      protein: "40g",
      calories: "300",
      energy: "1255kJ",
      carbs: "10g",
      fats: "8g",
    },
    "1kg": {
      protein: "80g",
      calories: "600",
      energy: "2510kJ",
      carbs: "20g",
      fats: "16g",
    },
  },
  {
    id: 19,
    name: "Eggplant and Lentil Stew",
    category: "Veg",
    ingredients: ["Eggplant", "Lentils", "Tomatoes", "Onions", "Spices"],
    "500g": {
      protein: "18g",
      calories: "220",
      energy: "920kJ",
      carbs: "35g",
      fats: "4g",
    },
    "1kg": {
      protein: "36g",
      calories: "440",
      energy: "1840kJ",
      carbs: "70g",
      fats: "8g",
    },
  },
  {
    id: 20,
    name: "Chicken Kebab",
    category: "Non-Veg",
    ingredients: ["Chicken", "Yogurt", "Spices", "Lemon"],
    "500g": {
      protein: "40g",
      calories: "350",
      energy: "1464kJ",
      carbs: "5g",
      fats: "10g",
    },
    "1kg": {
      protein: "80g",
      calories: "700",
      energy: "2928kJ",
      carbs: "10g",
      fats: "20g",
    },
  },
];

module.exports = { healthySmoothies, healthyBreakfasts, dinnerMeal};




 const allData = {
  "menu" : {
  "data" : {
    "scrollBar" : {},
      "topServe" : {},
    "cards" : {
      "healthySmoothies" : [
        {
          "id": 1,
  "name": "Infused Water",
  "starsRatings": "",
  "price": "",
  "imageURL": "https://images.pexels.com/photos/9009821/pexels-photo-9009821.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
  "protein": "0g",
  "calories": "5",
  "fats": "0g",
  "carbs": "1g",
  "category": "Pre-Workout"
},
{

},
{},

      ],
      "healthyBreakfasts" : {},
      "dinnerMeal" : {},
      "allMix": {}
    },
      "categories": {
        "pre-workout": {},
        "post-workout": {},
        "lessThan200": {},
        "rating>4": {}
      }
  }
  }
}
